# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "sandbox-studiosauce-s3-terraform"
    dynamodb_table = "sandbox-terraform-locks"
    encrypt        = true
    key            = "sandbox/us-east-1/development/cloudwatch/terraform.tfstate"
    region         = "us-east-1"
  }
}
